### ISSUE TITLE
Question about nerfdet results reported in your paper

### ISSUE THREAD

**Issue by Pixie8888** [SerCharles/CN-RMA#1]
Hi author,

I found that the nerfdet results reported in your paper (table 1 and table 2) are inconsistent with any existing papers. How did you get these results?

**Comment by SerCharles** [comment]
I directly run the code on the NeRFDet paper to get the ScanNet result using their provided checkpoint.
Since it does not provide official code and checkpoint on the ARKitScenes dataset, I slightly change the config, change the bbox_head to
`    bbox_head=dict(
        type='SunRgbdImVoxelHeadV2',
        n_classes=17,
        n_channels=128,
        n_reg_outs=7,
        n_scales=3,
        limit=27,
        centerness_topk=18),
`
following ImVoxelNet, which use the head on the OBB dataset of SUNRGBD, and get my result. This result is slightly higher than NeRFDet paper provided.
